---
title: "Workflow notes"
author: "Kyle McCarty & Marc"
date: "2/9/2025"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*If you have a problem in RStudio with checking commits, it may be a bug. Use RStudio's Terminal and run this command:

git commit -v -a

Then uncomment one line and enter. This should fix the rest of the unselectable commits.

# Air Quality Project

## 1. Package Arrives
  * Package list
    1. Raspberry Pi Zero W board
    2. Housing
    3. 2.5A power supply
    4. Heatsink
    5. Pimonori Enviro+ sensor board
    6. PMS5003 particulate matter sensor
    7. SD Card
    
    
## 2. Software for 2025: 

[https://www.rigacci.org/wiki/doku.php/doc/appunti/hardware/raspberrypi_air]

https://learn.pimoroni.com/article/getting-started-with-enviro-plus


OLD site: https://learn.pimoroni.com/article/enviro-plus-and-luftdaten-air-quality-station#testing-the-luftdaten-script




    
## 2. Install Raspberry Pi OS (previously Raspbian) on SD Card
* Use either a SD card slot or USB/SD card adapter on ***another*** computer to connect SD card for OS installation.
    1. Download Raspberry Pi Imager for your operating system (OS) at [https://www.raspberrypi.org/downloads/](https://www.raspberrypi.org/downloads/)
    2. Install Raspberry Pi Imager
    3. Use Raspberry Pi Imager to install/write Raspberry Pi OS to SD card.
        1. Customize with the following parameters: 
            * Choose OS: **Raspberry Pi OS (other)**
            * Choose SD Card: **Select the SD card you want to write the OS to**
            * Choose Storage: **Choose the size of the SD card**
            * Write: **Click "Write" to write the OS to the SD card**
            * Host: Pi#, where # is the number of the Pi you are using.

            
  11. Update Raspberry Pi Zero W.
  + To make sure the Raspberry Pi Zero W is up to date, run the following commands, one after the other, making sure the process completes each time:
  

```
sudo apt update
sudo apt full-upgrade

```

This can take 45 minutes with a newly imaged SD card. N


## 3. Install Pimoroni Enviro+ software
* To install the Pimoroni Enviro+ software, run the following command in the terminal:
```
git clone https://github.come/pimoroni/enviroplus-python
cd enviroplus-python
sudo ./install.sh
```

## 4. Test the Pimoroni Enviro+ software
* To test the Pimoroni Enviro+ software, run the following command in the terminal:
```
source ~/.virtualenvs/pimoroni/bin/activate
```

There are several examples in the examples folder within the enviroplus-python folder. In the terminal, type the following to look at the available examples:

```
cd enviroplus-python
cd examples
ls
```

## Clone Marc/Kyle's GitHub repository

* To clone the GitHub repository, run the following command in the terminal:
```
git clone https://github.com/marclos/EJnPi
```

## Test software... still working on this!!!


## Set up Script to Run automatically


An easy way of running a script automatically on boot is to use crontab, a job scheduler, which has an @reboot command that will run a script or command when the Pi first boots up.

In the terminal, type crontab -e and then select nano as the editor.

Scroll down to the very bottom of the file with the arrow keys and type the following line:
```
@reboot sudo python /home/pi/enviroplus-python/examples/luftdaten.py &
```

Double- and triple-check this command to make sure that it's exactly correct, as any error will cause it not to run on boot.

Press control-x, then y, then enter to exit and save the new crontab.

You should now shutdown your Raspberry Pi Zero W, either through the Raspberry Pi menu, or by typing sudo shutdown -h now in the terminal.


When running the examples that follow, you can type control-c at any time to stop the example running.

